### PR TITLE
generator the container's name when the image's name can not be used as container name

### PR DESCRIPTION
**Pull request by carmark**
Now, `hyper` will use image's name as the container's name, but the container's name can only be `^/?[a-zA-Z0-9][a-zA-Z0-9_.-]+$`.  So it will generator a new container's name randomly when the image's name is invalid for the rule of container's name.

### Test Result

```
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper run danielbodart/crazyfast.build
POD id is pod-oRxYYYiucq
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper list container
Container ID                                                      Name                         POD ID    Status
cbd68f11ed4a878d106ad1462aecfbbe1dbbb6c35718c35e26313975e2c5c128  berserk_mcclintock   pod-oRxYYYiucq    failed
```

### CODE REVIEW

**Comment by gnawux** [comment]
but what's the problem in the example? the slash?

I's the normal case a image name having a slash to separate the repo name and the image name. should we do a special process on slash?

**Comment by carmark** [comment]
@gnawux 

Yeah, the slash is invalid character in a container's name.

I also did think of doing a special process for that slash, but the user may not care about that container's name if container's name is not specified.   So a valid and random container's name should be all right.

**Comment by gnawux** [comment]
@carmark 

I don't think users care about it either. However, I think we should do things consistently. If we use image name as the container name prefix, then we should use `NNNNN` as name prefix of image `RRRR/NNNNN`. Otherwise, we should never use image name as the prefix for all cases.

**Comment by carmark** [comment]
sounds reasonable, I will update it.

**Comment by carmark** [comment]
@gnawux 

updated, could you please review it again?

**Comment by gnawux** [comment]
looks good

**Pull request merged**
