### PR TITLE
add rpm spec to the package

### PR DESCRIPTION
**Pull request by gnawux**
tested with fedora/x86_64, to be tested with CentOS 7
additional requirement: upstream go bin package, instead of go from repo

Signed-off-by: Wang Xu <gnawux@gmail.com>

### CODE REVIEW

**Comment by gnawux** [comment]
@carmark could you give me a config file with all configurable fields (and most of them are commented out) when you have time?

**Comment by carmark** [comment]
```
Kernel=/var/lib/hyper/kernel                   # Boot kernel for KVM/XEN
Initrd=/var/lib/hyper/hyper-initrd.img         # Boot initrd for KVM/XEN
Vbox=xxxx                                      # Boot image for vbox
Bios=/var/lib/hyper/bios-qboot.bin            
Cbfs=/var/lib/hyper/cbfs-qboot.rom
Bridge=
BridgeIP=
Host=                                          # Host address, same as the '--host' option
StorageDriver=overlay                          # Hyper storage backend driver
Root=xxxx                                      # Root directory for hyper
Hypervisor=kvm                                 # Hypervisor which is used by hyper
DisableIptables=false                          # Disable the iptables
Logger=xxxx                                    # Not sure???

```

**Comment by gnawux** [comment]
initial rpm for centOS 7 has been built and uploaded to S3

https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.src.rpm
https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.x86_64.rpm

**Comment by gnawux** [comment]
update: 

- add systemd service config file into rpm package
- add hyperstart rpm and set it as dependency of hyper

Build result for testing:

binary rpm:

- https://s3.amazonaws.com/hyper-install/hyper-0.4-2.el7.centos.x86_64.rpm
- https://s3.amazonaws.com/hyper-install/hyperstart-0.4-1.el7.centos.x86_64.rpm

src rpm:

- https://s3.amazonaws.com/hyper-install/hyper-0.4-2.el7.centos.src.rpm
- https://s3.amazonaws.com/hyper-install/hyperstart-0.4-1.el7.centos.src.rpm

**Comment by gnawux** [comment]
The docker image to generate the rpm has been pushed to official Docker hub: https://hub.docker.com/r/hyperhq/centos_builder/

**Pull request merged**
