### PR TITLE
fix device mapper build error with go 1.5

### PR DESCRIPTION
**Pull request by gnawux**
code from docker upstream

### CODE REVIEW

**Comment by gnawux** [comment]
when you compiled with 1.4 firstly, then switch to 1.5, this issue will caused a build error. And the patch is comes from docker.

**Comment by gnawux** [comment]
can not build under go 1.5.1/ubuntu without this patch, could you review and test this patch? @carmark @laijs

**Comment by carmark** [comment]
Test cases **passed**, code LGTM

```
lei@ubuntu:~/src/github.com/hyperhq/hyper$ make
make[1]: Entering directory `/home/lei/src/github.com/hyperhq/hyper'
go build -tags "static_build libdm_no_deferred_remove" -ldflags "-X github.com/hyperhq/hyper/utils.VERSION 0.4.0" hyperd.go
# command-line-arguments
link: warning: option -X github.com/hyperhq/hyper/utils.VERSION 0.4.0 may not work in future releases; use -X github.com/hyperhq/hyper/utils.VERSION=0.4.0
go build -ldflags "-X github.com/hyperhq/hyper/utils.VERSION 0.4.0" hyper.go
# command-line-arguments
link: warning: option -X github.com/hyperhq/hyper/utils.VERSION 0.4.0 may not work in future releases; use -X github.com/hyperhq/hyper/utils.VERSION=0.4.0
make[1]: Leaving directory `/home/lei/src/github.com/hyperhq/hyper'
lei@ubuntu:~/src/github.com/hyperhq/hyper$ go version
go version go1.5beta1 linux/amd64
lei@ubuntu:~/src/github.com/hyperhq/hyper$ git status
On branch rmi
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   lib/docker/pkg/devicemapper/devmapper_wrapper.go

no changes added to commit (use "git add" and/or "git commit -a")
lei@ubuntu:~/src/github.com/hyperhq/hyper$
```

**Comment by laijs** [comment]
LGTM

**Pull request merged**
