### PR TITLE
Fix rbd volume for libvirt driver

### PR DESCRIPTION
**Pull request by feiskyer**
Fix https://github.com/hyperhq/runv/pull/109 https://github.com/hyperhq/runv/pull/108

Depends on https://github.com/hyperhq/runv/pull/110

### CODE REVIEW

**Comment by gnawux** [comment]
should not modify the code under Godep directly. code here will be overwritten when we update the dependencies.

**Comment by feiskyer** [comment]
Here is indeed a dependency update. We can't wait for libvirt-go upstream to accept it.

**Comment by laijs** [comment]
then you should also update the Godeps.json

**Comment by feiskyer** [comment]
sure

**Pull request merged**
