### PR TITLE
[update-demo-png] update the demo picture after hyper upgrade to 0.4.0

### PR DESCRIPTION
**Pull request by Jimmy-Xu**

### CODE REVIEW

**Comment by gnawux** [comment]
I think the hyper run will show the shell prompt in the ubuntu container.

**Comment by feiskyer** [comment]
```
# hyper run centos:latest
POD id is pod-lxpCHxfANR
bash-4.2#
```

**Comment by Jimmy-Xu** [comment]
picutre updated. added some details for demo script.

**Comment by laijs** [comment]
good

**Pull request merged**
