### PR TITLE
pull the images in pod file automatically while creating pod

### PR DESCRIPTION
**Pull request by carmark**
```
lei@leis-MacBook-Pro:[hyper] (pull_login)$ ./hyper create examples/test.pod
latest: Pulling from busybox
cf2616975b4a: Pull complete
6ce2e90b0bc7: Pull complete
8c2e06607696: Pull complete
Digest: sha256:df9e13f36d2d5b30c16bfbf2a6110c45ebed0bfa1ea42d357651bc6c736d5322
Status: Downloaded newer image for busybox:latest
Pod ID is pod-TULrekKtvx
lei@leis-MacBook-Pro:[hyper] (pull_login)$ ./hyper images
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
puller         latest              100000000000                2015-07-18 06:01:13                 0 B
busybox        latest              8c2e06607696                2015-04-18 06:01:13              2.3 MB
lei@leis-MacBook-Pro:[hyper] (pull_login)$ ./hyper list
         POD ID                      POD Name             VM name    Status
 pod-TULrekKtvx   test-container-create-ubunt                       pending
lei@leis-MacBook-Pro:[hyper] (pull_login)$
```

### CODE REVIEW

**Comment by laijs** [comment]
it is better to (automatically) pull the image only after the server report the image is missing(404).
otherwise
1) the pulling may be blocked or failed due to network
2) the (existing) image is changed (the user expects that the image must be the one in his currently repository)

**Comment by carmark** [comment]
@laijs Yeah, it should be. I will modify it.

**Comment by carmark** [comment]
Could you please review it again with the updated patch? @laijs 

And the test result is:

Without fix:

```
lei@leis-MacBook-Pro:[hyper] (master)$ ./hyper images
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
puller         latest              100000000000                2015-07-18 06:01:13                 0 B
busybox        latest              8c2e06607696                2015-04-18 06:01:13              2.3 MB
lei@leis-MacBook-Pro:[hyper] (autopull)$ ./hyper create examples/ubuntu.pod
./hyper ERROR: could not find image: no such id: 8251da35e7a79dca688682f6da6148a06d358c6f094020844468a782842c2172
```

With fix:

```
lei@leis-MacBook-Pro:[hyper] (autopull)$ ./hyper images
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
puller         latest              100000000000                2015-07-18 06:01:13                 0 B
busybox        latest              8c2e06607696                2015-04-18 06:01:13              2.3 MB
lei@leis-MacBook-Pro:[hyper] (autopull)$ ./hyper create examples/ubuntu.pod
latest: Pulling from ubuntu
d3a1f33e8a5a: Pull complete
c22013c84729: Pull complete
d74508fb6632: Pull complete
91e54dfb1179: Already exists
ubuntu:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:fde8a8814702c18bb1f39b3bd91a2f82a8e428b1b4e39d1963c5d14418da8fba
Status: Downloaded newer image for ubuntu:latest
Pod ID is pod-UFRYUuCCec
lei@leis-MacBook-Pro:[hyper] (autopull)$ ./hyper images
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
ubuntu         latest              91e54dfb1179                2015-08-21 04:21:15            179.6 MB
puller         latest              100000000000                2015-07-18 06:01:13                 0 B
busybox        latest              8c2e06607696                2015-04-18 06:01:13              2.3 MB
lei@leis-MacBook-Pro:[hyper] (autopull)$ ./hyper list
         POD ID                      POD Name             VM name    Status
 pod-TULrekKtvx   test-container-create-ubunt                       pending
 pod-bAnFGVNYMn            busybox-6252283306                       pending
 pod-UFRYUuCCec   test-container-create-ubunt                       pending
lei@leis-MacBook-Pro:[hyper] (autopull)$
```

**Comment by laijs** [comment]
LGTM, merge

**Pull request merged**
