### PR TITLE
add portmap setup options for 'run' command

### PR DESCRIPTION
**Pull request by carmark**

### CODE REVIEW

**Comment by laijs** [comment]
code LGTM

**Comment by gao-feng** [comment]
only for tcp protocol?

**Comment by carmark** [comment]
@gao-feng Yes, I noticed that there is no protocol configured by docker.

```
-p, --publish=[]           Publish a container's port to the host
                               format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort
                               (use 'docker port' to see the actual mapping)
```

**Comment by gao-feng** [comment]
LGTM

**Comment by nuxlli** [comment]
:+1:

**Pull request merged**
